- typings/psycopg2/sql.pyi
We can do better than Any for the wrapped param
> fix(pyscopg2): sql module Composable param type

- typings/django/contrib/admin/__init__.pyi
I forgot this important step in #37.
> Expose new admin decorators in django.contrib.admin

- django-stubs/db/models/deletion.pyi
Django 3.1 updated these db deletion errors to show the set of all objects that protected/restricted the deletion, as opposed to just the model of one object. 
As such, these stubs need to be updated. This matches how these errors are typed in `typeddjango`.
> Update ProtectedError and RestrictedError stubs 

- django-stubs/db/models/fields/__init__.pyi
I do not know if there was a particular reason for why it was not implemented before. But, I took the liberty to mimic what was done for similar fields on the upstream.
Essentially, The `__init__` was overloaded to distinguish between `null=True` and `null=False` to signal the resulting type, `Optional[date]` or `date` respectively.
> Allow DateField to be Optional

- django-stubs/contrib/postgres/fields/array.pyi
- django-stubs/db/models/fields/__init__.pyi
- s/lint
- tests/pyright/base.py
- tests/pyright/test_fields.py
- tests/trout/models.py
This was built on top of https://github.com/sbdchd/django-types/pull/63, so merging it should only keep this PR's change
Note that even though the change looks big, it actually is pretty small, it is just that all fields need to define their own `__new__` (or `__init__` if their signature is different from the base field), and it is all the same, the difference is the classname and the generic field. I also added some documentation [here](https://github.com/sbdchd/django-types/pull/65/files#diff-876a5d116ef70c86039fbb8498623871324fa93fc1ae51c7c09ba2a0f7612e99R47) explaining the usage.
Fix https://github.com/sbdchd/django-types/issues/34
> Fields typing improvements

- README.md
https://github.com/django/django/pull/12405#issuecomment-596109039
QuerySet and BaseManager already have __class_getitem__, starting from Django 3.1
> Fix typo and Django version requirements in Readme

- django-stubs/db/models/fields/__init__.pyi
- django-stubs/db/models/fields/json.pyi
- django-stubs/db/models/fields/related.pyi
- tests/pyright/test_migrations.py
Just upgraded to 0.11.0 and notice some errors on my migrations. There's no need to set covariant/contravariant on _GT/_ST.
The tests are just there to make sure that there are no errors anymore. If the code is reverted the test would fail
> Fix migration issues for fields with choices

- django-stubs/db/models/fields/related.pyi
I think that it was removed in one of the recent PRs for improving `ManyToManyField` typing.
> Add db_table kwarg to ManyToManyField constructor

- django-stubs/db/models/manager.pyi
From the docs for `add()`:
https://docs.djangoproject.com/en/4.0/ref/models/relations/#django.db.models.fields.related.RelatedManager.add
> For many-to-many relationships add() accepts either model instances or field values, normally primary keys, as the *objs argument.
Likewise for `remove()`:
https://docs.djangoproject.com/en/4.0/ref/models/relations/#django.db.models.fields.related.RelatedManager.remove
> For many-to-many relationships remove() accepts either model instances or field values, normally primary keys, as the *objs argument.
> Allow adding and removing field values (typically primary keys) in many-to-many relationships.

- django-stubs/db/models/fields/files.pyi
Argument ordering was incorrect, actually they are in following order:
- verbose_name
- name
- upload_to
- storage
https://github.com/django/django/blob/2d8232fa716f5fe46eec9f35a0e90c2d0f126279/django/db/models/fields/files.py#L228
> fix: Fix argument ordering for FileField

- django-stubs/db/models/fields/files.pyi
https://docs.djangoproject.com/en/4.0/ref/models/fields/#django.db.models.FileField.upload_to
```python
if callable(self.upload_to):
filename = self.upload_to(instance, filename)
else:
dirname = datetime.datetime.now().strftime(str(self.upload_to))
filename = posixpath.join(dirname, filename)
```
> Set correct types if `upload_to` is a function

- django-stubs/db/models/fields/files.pyi
Any for upload_to is more useful, as it allows to specify concrete type in callback without triggering error.
> Allow `Any` in upload_to callback

- django-stubs/db/models/fields/related.pyi
By the way, why other typings here using ` = ...`?
Should i also add `= ...` to this line?
> fix: Add `through` to ManyToManyField

- django-stubs/test/testcases.pyi
I discovered annotations for `assertQuerysetEqual` are incorrect, so I fixed them.
> Fix assertQuerysetEqual annotations

- django-stubs/db/models/base.pyi
Addresses https://github.com/microsoft/pylance-release/issues/3918
As currently defined, type checkers see the `Model.DoesNotExist` and `Model.MultipleObjectsReturned` exception types as being the same on all `Model` types.
I'm replacing the exception `class` declarations on `Model` with `ClassVar` so each `Model` type will have a distinct set of exception types, allowing the usage below without type checkers thinking that the later `except` clauses are unreachable.
```python
from django.db import models
class User(models.Model):
email = models.EmailField(max_length=250)
class Notification(models.Model):
message = models.CharField(max_length=250)
class Media(models.Model):
file = models.FileField()
def do_things(user_id: int, notification_id: int, media_id: Media) -> None:
try:
user = …
```
> Replace exception classes with ClassVars

- django-stubs/db/migrations/operations/models.pyi
This adds the `RenameIndex` operation which is part of Django since 4.1 (https://docs.djangoproject.com/en/4.2/ref/migration-operations/#renameindex).
> Add RenameIndex migrate operation

- django-stubs/contrib/contenttypes/models.pyi
The `permission_set` reverse lookup was previously undefined on ContentType.
> Add `permission_set` reverse lookup to ContentType.

- django-stubs/test/testcases.pyi
Adds the [`TransactionTestCase.assertQuerySetEqual` method][0], which is the non-deprecated version of `TransactionTestCase.assertQuerysetEqual`, which was deprecated in Django 4.2 and is set to be removed in Django 5.1.
I don't know of a way with type annotations to copy the signature of one method to another, so I just copy-pasted them, while also making some improvements with generic types.
[0]: https://docs.djangoproject.com/en/4.2/topics/testing/tools/#django.test.TransactionTestCase.assertQuerySetEqual
> Add TransactionTestCase.assertQuerySetEqual

- django-stubs/test/testcases.pyi
Support cases such as
```python
result: Iterable[Tuple[Any, ...]] =  [(...), (...)]
self.assertQuerySet(MyModel.objects.values_list(...), result, transform=tuple)
```
> Support ValuesQuerySet in assertQuerySetEqual

- django-stubs/db/models/fields/__init__.pyi
- Add `allow_unicode` to SlugField (see: https://docs.djangoproject.com/en/5.0/ref/models/fields/#slugfield)
> Add allow_unicode to SlugField

- django-stubs/urls/conf.pyi
Allows to pass NinjaAPI's ``.urls`` to Django's ``path`` function.
Adding ``URLPattern`` to ``IncludedURLConf`` didn't work. My guess is that this is caused by the `str | None` in ``IncludedURLConf`` which is not as strict as the return type of ``ninja_api.urls``
fixes sbdchd/django-types#173
> Add another overload to path function

- django-stubs/contrib/auth/models.pyi
Adds managers for reverse names of many to many relationships in the contrib.auth app.
This is a small QoL improvement PR. It provides type checkers with the reverse relationships between:
- Group and Permission: Permission has a typed `.group_set` manager object
- PermissionMixin and Group: Group has a typed `.user_set` manager object
The reasons for using _PermissionMixin_ rather than other possible models/mixins are (1) the relationship is defined in the mixin to begin with, and (2) this is compatible with any model that inherits the mixin - e.g. AbstractUser, User, or a custom user model.
> Add ManyToManyRelatedManager to auth models

- django-stubs/test/client.pyi
Closes #144
This seems straightforward, but I'm not writing a lot of .pyi files. I have tested it briefly and it seems to work.
> Add headers parameter to django.test.{RequestFactory,Client} methods

- django-stubs/utils/deconstruct.pyi
Adds generic type hints to [`@deconstructible`](https://docs.djangoproject.com/en/4.2/topics/migrations/#adding-a-deconstruct-method) so that it preserves the implicit types of the class it decorates.
I don't know of a way to indicate that the class it returns has a `decorator()` method attached to it.
> `django.utils.deconstruct`: Improve types

- django-stubs/test/client.pyi
This seems to work for me but I'm not sure how one generally goes about generating these signatures nor how to validate them.
> django.test.client: add AsyncClient and dependencies

- django-stubs/db/models/fields/json.pyi
KT shortcut is actually an alias for KeyTextTransform.from_lookup class method. Annotated classmethod and then assigned alias.
> KT is a function, not an instance.

- django-stubs/db/models/fields/__init__.pyi
Allow CharField(choices=...) to be a TextChoices class.
Changed in Django 5.0, see note here: https://docs.djangoproject.com/en/5.0/ref/models/fields/#s-enumeration-types
> Allow text choices being directly assigned as choices.

- django-stubs/test/testcases.pyi
Fix `assertJSON*` annotations to match all supported input types.
> Fix annotations for assertJSON*

- django-stubs/core/mail/__init__.pyi
When given None as from_email Django uses the DEFAULT_FROM_EMAIL setting.
> Allow passing None as from_email to send_mass_mail

- django-stubs/core/exceptions.pyi
use a recursive type definition for `ValidationError` to match the [actual implementation (4.2)](https://github.com/django/django/blob/7bd1ddf1d81e9120c28322ee2a0b9c11941a6af2/django/core/exceptions.py#L133-L178)
should resolve #280
> ValidationError message argument is recursively defined

- django-stubs/utils/translation/__init__.pyi
Refs https://docs.djangoproject.com/en/5.1/topics/i18n/translation/#lazy-translations-and-plural
> fix: Third argument for ngettext_lazy is optional

- django-stubs/http/request.pyi
- Added `current_app` to `HttpRequest`.
- Added comments to the same section of HttpRequest and used `_AnyUser` instead of `AbstractBaseUser | AnonymousUser` a la [django-stubs](https://github.com/typeddjango/django-stubs/blob/01c1c03acd468dace6fc42556b59d6a9967dfa5b/django-stubs/http/request.pyi#L53-L65).
closes #253
> Add `current_app` to `HttpRequest`

- README.md
closes #216 
- Fixed the broken link to `django_stubs_ext` in the README.md file.
- Added an additional header to this section because monkeypatching instructions _appeared_ to fall under the "install" heading giving the impression that this is mandatory, when in fact it only applies to old Django versions and probably isn't required for most users now.
> Fix link to `django_stubs_ext` in README.md

- django-stubs/test/client.pyi
`**extra` ends up in `request.META` which can contain things like `CSRF_COOKIE_USED = True`, so use `object` type to allow anything.
> `RequestClient.request(**extra)` META can include non-str

- django-stubs/urls/base.pyi
New in Django 5.2
Fixed the mypy failures with the previous version
> Add `query` and `fragment` parameters to `reverse` type definition

- django-stubs/contrib/admin/decorators.pyi
This fixes subclassing ModelAdmin that's been @register()'d
> contrib.admin.decorators: use TypeVar

- django-stubs/contrib/admin/options.pyi
- django-stubs/contrib/admin/views/autocomplete.pyi
- django-stubs/contrib/admin/views/main.pyi
- django-stubs/contrib/syndication/views.pyi
- django-stubs/core/exceptions.pyi
Ran `./s/lint` and found that Black reformatted a few files, mostly because of whitespace.
> Fix Black formatting violations.

- django-stubs/db/models/enums.pyi
[Django 5.0 deprecates ChoicesMeta](https://docs.djangoproject.com/en/5.2/releases/5.0/#features-deprecated-in-5-0) favour of `ChoicesType` (renamed).
Ported the equivalent [django-stubs change for this deprecation](https://github.com/typeddjango/django-stubs/pull/1942).
> [Django 5.0] ChoicesType type alias for ChoicesMeta
